---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
        standard: "phpcs.xml"
ratings:
  paths:
    - "**.js"
    - "**.php"
exclude_paths:
  - node_modules/**/*
  - languages/**
  - lib/cloudinary/**
  - lib/plugin-customizer/assets/twentysixteen/**
  - lib/Customizer/assets/js/boxshadow.js
